### ISSUE TITLE
Hi, is this the code for the TOF LiDAR from aliexpress?

### ISSUE THREAD

**Issue by Vidicon** [seishinkouki/LidarTestGUI#1]
https://www.aliexpress.com/item/1005007119470172.html

**Comment by seishinkouki** [comment]
yes

**Comment by heqichen** [comment]
Hi, do you know the distance range of this LiDAR?

**Comment by seishinkouki** [comment]
> Hi, do you know the distance range of this LiDAR?

I think the range is 100mm-10000mm
